<a href="https://colab.research.google.com/github/akritivishwakarma2007/DE-journey/blob/main/Numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[44, 35,  7, 56],
       [87, 61, 33, 16],
       [51,  6, 98, 62],
       [59, 20, 24, 57],
       [21, 15, 20, 14],
       [82, 73, 10, 27]])

In [4]:
np.sort(a)[::-1]

array([91, 88, 82, 80, 72, 56, 53, 30, 24, 21, 15, 11,  9,  7,  4])

In [7]:
np.sort(b, axis = 0)

array([[21,  6,  7, 14],
       [44, 15, 10, 16],
       [51, 20, 20, 27],
       [59, 35, 24, 56],
       [82, 61, 33, 57],
       [87, 73, 98, 62]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array



In [8]:
# code
np.append(a,200)

array([  4,  56,  53,  24,  21,  91,   7,  80,  72,  15,  11,  30,  82,
        88,   9, 200])

In [9]:
b

array([[44, 35,  7, 56],
       [87, 61, 33, 16],
       [51,  6, 98, 62],
       [59, 20, 24, 57],
       [21, 15, 20, 14],
       [82, 73, 10, 27]])

In [11]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[44.        , 35.        ,  7.        , 56.        ,  0.1597825 ],
       [87.        , 61.        , 33.        , 16.        ,  0.38602374],
       [51.        ,  6.        , 98.        , 62.        ,  0.20266355],
       [59.        , 20.        , 24.        , 57.        ,  0.16482896],
       [21.        , 15.        , 20.        , 14.        ,  0.85036228],
       [82.        , 73.        , 10.        , 27.        ,  0.78809431]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [12]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.



In [15]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array


In [17]:
# code
a.shape

(15,)

In [18]:
np.expand_dims(a,axis=0)

array([[ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9]])

In [19]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1)

array([[ 4],
       [56],
       [53],
       [24],
       [21],
       [91],
       [ 7],
       [80],
       [72],
       [15],
       [11],
       [30],
       [82],
       [88],
       [ 9]])

In [21]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.


In [22]:
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [23]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  2,  5,  7,  8, 12, 13]),)

In [24]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 4,  0,  0, 24, 21,  0,  7,  0,  0, 15, 11, 30,  0,  0,  9])

In [25]:
np.where(a%2 == 0,0,a)

array([ 0,  0, 53,  0, 21, 91,  7,  0,  0, 15, 11,  0,  0,  0,  9])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [26]:
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [27]:
np.argmax(a)

np.int64(5)

In [28]:
b

array([[44, 35,  7, 56],
       [87, 61, 33, 16],
       [51,  6, 98, 62],
       [59, 20, 24, 57],
       [21, 15, 20, 14],
       [82, 73, 10, 27]])

In [30]:
np.argmax(b,axis = 0)

array([1, 5, 2, 2])

In [31]:
np.argmax(b,axis=1)

array([3, 0, 2, 0, 0, 0])

In [32]:
# np.argmin
np.argmin(a)

np.int64(0)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.



In [33]:
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [34]:
np.cumsum(a)

array([  4,  60, 113, 137, 158, 249, 256, 336, 408, 423, 434, 464, 546,
       634, 643])

In [35]:
b

array([[44, 35,  7, 56],
       [87, 61, 33, 16],
       [51,  6, 98, 62],
       [59, 20, 24, 57],
       [21, 15, 20, 14],
       [82, 73, 10, 27]])

In [36]:
np.cumsum(b, axis = 1)

array([[ 44,  79,  86, 142],
       [ 87, 148, 181, 197],
       [ 51,  57, 155, 217],
       [ 59,  79, 103, 160],
       [ 21,  36,  56,  70],
       [ 82, 155, 165, 192]])

In [37]:
np.cumsum(b)

array([ 44,  79,  86, 142, 229, 290, 323, 339, 390, 396, 494, 556, 615,
       635, 659, 716, 737, 752, 772, 786, 868, 941, 951, 978])

In [38]:
#cumprod()
np.cumprod(a)

array([                   4,                  224,                11872,
                     284928,              5983488,            544497408,
                 3811481856,         304918548480,       21954135490560,
            329312032358400,     3622432355942400,   108672970678272000,
        8911183595618304000, -9025838755099967488, -7445572501061500928])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [39]:
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [45]:
np.percentile(a,50)

np.float64(30.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.



In [50]:
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [52]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([5, 3, 2, 1, 4]), array([  0,  20,  40,  60,  80, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

In [53]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.


In [54]:
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [56]:
np.isin(a, [20,53,30])

array([False, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False])

In [58]:
a[np.isin(a, [20,53,30])]

array([53, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.


In [59]:
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [60]:
np.flip(a)

array([ 9, 88, 82, 30, 11, 15, 72, 80,  7, 91, 21, 24, 53, 56,  4])

In [61]:
b

array([[44, 35,  7, 56],
       [87, 61, 33, 16],
       [51,  6, 98, 62],
       [59, 20, 24, 57],
       [21, 15, 20, 14],
       [82, 73, 10, 27]])

In [62]:
np.flip(b,axis=1)

array([[56,  7, 35, 44],
       [16, 33, 61, 87],
       [62, 98,  6, 51],
       [57, 24, 20, 59],
       [14, 20, 15, 21],
       [27, 10, 73, 82]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.


In [63]:
a

array([ 4, 56, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [66]:
np.put(a,[0,1],[7,40])

In [67]:
a

array([ 7, 40, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.


In [68]:
a

array([ 7, 40, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [70]:
np.delete(a, [1])

array([ 7, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [71]:
np.delete(a, [2,5,9])

array([ 7, 40, 24, 21,  7, 80, 72, 11, 30, 82, 88,  9])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [72]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
np.intersect1d(m,n)

array([3, 4, 5])

In [74]:
np.setdiff1d(m,n)

array([1, 2])

In [75]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [78]:
np.in1d(m,2)

/tmp/ipykernel_6958/595628413.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,2)


array([False,  True, False, False, False])

In [79]:
m[np.in1d(m,2)]

/tmp/ipykernel_6958/1121211304.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,2)]


array([2])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.



In [80]:
a

array([ 7, 40, 53, 24, 21, 91,  7, 80, 72, 15, 11, 30, 82, 88,  9])

In [81]:
np.clip(a,a_min=25,a_max=75)

array([25, 40, 53, 25, 25, 75, 25, 75, 72, 25, 25, 30, 75, 75, 25])