<a href="https://colab.research.google.com/github/akritivishwakarma2007/DE-journey/blob/main/Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Creating Numpy Arrays

In [2]:
#np.array
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D 3D array

b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(type(c))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [10]:
#dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [12]:
#np.arange
#arange(start,stop,step)
np.arange(1,11)
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
#with reshape
#reshape(row,col)
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [17]:
#np.ones and np.zeros
#np.ones(rows,cols)
np.ones((3,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#np.zeros(rows,cols)
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
#np.random
np.random.random((3,2))

array([[0.16188694, 0.3619401 ],
       [0.83280096, 0.26663396],
       [0.70259182, 0.09127784]])

In [28]:
#np.linspace
print(np.linspace(-10,10,10))
np.linspace(-10,10,10, dtype= int)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [26]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##Array Attributes

In [50]:
a1 = np.arange(11,dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [39]:
#ndim -> dimension
a3.ndim

3

In [43]:
#shape
print(a2.shape)
print(a2)

(3, 4)
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [44]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [51]:
#itemsize
a1.itemsize

4

In [53]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64
