<a href="https://colab.research.google.com/github/akritivishwakarma2007/DE-journey/blob/main/Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Creating Numpy Arrays

In [2]:
#np.array
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D 3D array

b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(type(c))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [10]:
#dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [12]:
#np.arange
#arange(start,stop,step)
np.arange(1,11)
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
#with reshape
#reshape(row,col)
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [17]:
#np.ones and np.zeros
#np.ones(rows,cols)
np.ones((3,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#np.zeros(rows,cols)
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
#np.random
np.random.random((3,2))

array([[0.16188694, 0.3619401 ],
       [0.83280096, 0.26663396],
       [0.70259182, 0.09127784]])

In [28]:
#np.linspace
print(np.linspace(-10,10,10))
np.linspace(-10,10,10, dtype= int)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [26]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##Array Attributes

In [50]:
a1 = np.arange(11,dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [39]:
#ndim -> dimension
a3.ndim

3

In [43]:
#shape
print(a2.shape)
print(a2)

(3, 4)
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [44]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [51]:
#itemsize
a1.itemsize

4

In [53]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


##Changing Datatype

In [59]:
#astype
a3.astype(float)
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

##Array Operations

In [62]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
#Scalar operations

#Arithematic
print(a1 * 2)
print(a1 + 2)
print(a1 - 2)
print(a1 / 2)
print(a1 ** 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [69]:
#relational operators
print(a2>20)

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [71]:
#vector Operations
#Arithematic
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


##Array Fumctions

In [73]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[40., 54., 21.],
       [86., 46., 76.],
       [89., 33., 47.]])

In [77]:
#max/min/sum/product
#0 -> cols , 1 -> row
print(np.max(a1,axis = 0))
print(np.min(a1,axis = 1))
print(np.sum(a1,axis = 1))
print(np.prod(a1, axis = 1))


[89. 54. 76.]
[21. 46. 33.]
[115. 208. 169.]
[ 45360. 300656. 138039.]


In [79]:
#mean/median/std/var
print(np.mean(a1, axis = 0))
print(np.median(a1, axis = 0))
print(np.std(a1, axis = 0))
print(np.var(a1, axis = 0))

[71.66666667 44.33333333 48.        ]
[86. 46. 47.]
[22.42518426  8.65383666 22.46478726]
[502.88888889  74.88888889 504.66666667]


In [80]:
#trignometric function
np.sin(a1)

array([[ 0.74511316, -0.55878905,  0.83665564],
       [-0.92345845,  0.90178835,  0.56610764],
       [ 0.86006941,  0.99991186,  0.12357312]])

In [81]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [82]:
#log and exponents
np.exp(a1)
np.log(a1)


array([[3.68887945, 3.98898405, 3.04452244],
       [4.4543473 , 3.8286414 , 4.33073334],
       [4.48863637, 3.49650756, 3.8501476 ]])

In [87]:
#round/floor/ceil
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))


[[21.  4. 42.]
 [56.  2. 19.]]
[[68. 70. 95.]
 [64. 53. 79.]]
[[26. 61. 54.]
 [32. 34.  8.]]
